Repository haasad/EcoInventDownLoader, pull requests merged in 2022-04, with the labels that each got.

#26 Add compatibility with brightway25
  README.md
  conda-recipe/meta.yaml
  eidl/core.py
Labels: enhancement

#27 Run tests for python 3.10
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
Labels: dependency

#28 Exclude files that user is not allowed to download
  eidl/core.py
Labels: bug
